### ISSUE TITLE
Add scalacheck-datetime section

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/exercises-scalacheck#16]
Scala Exercises features content for Scalacheck. @noelmarkham has developed scalacheck-datetime, library used for working with Date Time related precision constrained for `Arbitrary` and `Gen` instances.

Instead of creating a new Library for scalacheck-datetime we are going to merge the content of whatever exercises can be written for it so they show up under the scalacheck top level library.

More info about scalacheck-datetime here:
https://47deg.github.io/scalacheck-datetime/docs

**Comment by shiv4nsh** [comment]
@raulraja : Can we have some more insight what we have to do here ?

**Comment by raulraja** [comment]
@shiv4nsh Description updated, thanks!.
