### ISSUE TITLE
Exercise review comments

### ISSUE THREAD

**Issue by noelmarkham** [scala-exercises/exercises-scalacheck#6]
As discussed, my comments from these exercises. I think they're really good.

**Properties**
 * The `sqrt` function returns `Double`, not `Int`, even though (for example) `9.0 == 9`. But the property provided does not work for negative numbers. While I understand this is only an example, and thus it doesn't matter if the property holds or not, I would suggest it would be clearer if the property holds, and is unambiguous.
 * I think the explanation of _implication_ could be better.
 * The implication example (`(n == 0) ==> (n == 0)`) is a bit confusing. I think it would be better if the implication was different to the property.
 * In _Combining Properties_, have both `forAll`s at the same indent level, as I thought these were nested.
 * I think the _Grouping Properties_ section is confusing because the `ZeroSpecification` class takes a parameter, which (I think) is only ever `0`. I think it would just be clearer if the `value` parameter is removed and simply replaced with `0`.

**Generators**
 * Be consistent with `{` and `(` on the `check` methods.

I can't think of any headline items to add, perhaps you may want to show a property that actually fails, and perhaps how to label properties and generators.

I've not done a language review on this either, please let me know if you want me to do that.

I'll leave these suggestions to you, but I'm happy to help if you need it.

**Comment by fedefernandez** [comment]
Hi @noelmarkham 

Thanks for the feedback. I've created a PR that address a couple of suggestions (`forAll` indentation and consistency with `{` and `(`). See #7

Also, I've created an issue to improve the _Grouping Properties_ section. We need to figure out how to improve the exercise and let the user introduce some value. See #8

Related with the three first bullets and the lang review, practically all texts has been taken from the [User Guide](https://github.com/rickynils/scalacheck/blob/master/doc/UserGuide.md) but we could improve them.

Please, feel free to create any PRs or leave me more suggestions, any help will be very appreciated.

Thanks

**Comment by noelmarkham** [comment]
Ok, regarding the first three bullets:

 * I've just looked at this in the documentation, and it is explained that it fails there. I'd suggest:
  - Keep the `sqrt` as-is (I can live with the `double`/`int` discrepancy), but show the failure text (just like the ScalaCheck docs). 
  - Include another example before the sqrt example of a property passing (the ScalaCheck docs has list concatenation - that seems fine to me).
 * I've reread the implication explanation, and it's fine.
 * How about `(n == 0) ==> n + 10 == 10`
